# Generated by Django 3.1 on 2021-05-29 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='appuser',
            fields=[
                ('u_id', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='records',
            fields=[
                ('r_id', models.IntegerField(primary_key=True, serialize=False)),
                ('r_date_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='schedule',
            fields=[
                ('s_id', models.IntegerField(primary_key=True, serialize=False)),
                ('s_schedule', models.TextField()),
                ('s_data', models.DateField()),
                ('s_time', models.TimeField()),
                ('s_load_data_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='usertext',
            fields=[
                ('title', models.CharField(default='每日好心情', max_length=128, primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('r', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database_app.records')),
            ],
        ),
        migrations.CreateModel(
            name='save_s',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database_app.schedule')),
                ('u', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database_app.appuser')),
            ],
        ),
        migrations.CreateModel(
            name='save_r',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database_app.records')),
                ('u', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database_app.appuser')),
            ],
        ),
        migrations.CreateModel(
            name='photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='images/%Y/%m/%d/')),
                ('r', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database_app.records')),
            ],
        ),
    ]
