# Generated by Django 3.1 on 2021-06-02 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='photo',
            new_name='img',
        ),
    ]
