# Generated by Django 3.1 on 2021-06-05 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database_app', '0002_auto_20210602_1648'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='s_time',
        ),
    ]
