# Generated by Django 3.1 on 2021-06-08 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database_app', '0003_remove_schedule_s_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='s_load_data_time',
        ),
    ]
