# Generated by Django 3.1 on 2021-06-08 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database_app', '0004_remove_schedule_s_load_data_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='s_data',
            new_name='s_date',
        ),
    ]
