# Generated by Django 3.1 on 2021-06-18 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database_app', '0005_auto_20210608_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='img',
            field=models.ImageField(upload_to='static/save_images/%Y/%m/%d/'),
        ),
    ]
